server:
  port: 8080
  servlet:
    context-path: /app
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/cita
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: michael00455@gmail.com
    password: xfruryrqlozhpksb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true